version: "3.3"
services:
    web:
        build:
            context: ./docker
            dockerfile: Dockerfile
        container_name: php73
        depends_on:
            - db
        volumes:
            - ./public:/var/www/html/
        ports:
            - 80:80
            - 443:443
    db:
        container_name: mysqlB
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: phoenix
            MYSQL_USER: devuser
            MYSQL_PASSWORD: devpass
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - 6033:3306
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            PMA_PORT: 6033
        restart: always
        ports:
            - 3000:80
